version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    rebase-strategy: auto
    groups:
      patch-updates:
        patterns: ["*"]
        update-types: [patch]
      minor-updates:
        patterns: ["*"]
        update-types: [minor]
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
